server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
      - id: customer-service
        uri: http://localhost:8084
        predicates:
          - Path=/clients/**,comptes/**
      - id: catalogue
        uri: lb://catalogue-service
        predicates:
          - Path=/categories/**,/produits/**
          
        filters:
         
         - AddResponseHeader=abc,123
                  
  application:
    name: gateway-service

    
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    
    web:
      exposure:
        include: "*"
    